const $=s=>document.querySelector(s);
let state={upiId:'',name:'',amount:0,plan:[],currentIndex:0,returning:false};
let stream=null,deferredPrompt=null;
const screens=['home','manual','scanner','details','apps','returnConfirm','history'];
function show(id){screens.forEach(x=>$('#'+x)?.classList.toggle('active',x===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'})}
function parseUPI(raw){try{if(!raw.startsWith('upi://pay'))return null;const u=new URL(raw),p=Object.fromEntries(u.searchParams.entries());return p.pa?{upiId:p.pa,name:p.pn||'UPI Merchant',amount:p.am||''}:null}catch(e){return null}}
function setDetails(d){state={...state,upiId:d.upiId,name:d.name||'UPI Merchant'};$('#upiId').textContent=d.upiId;$('#merchantName').textContent=d.name||'UPI Merchant';$('#amount').value=d.amount||'';$('#amountHint').textContent='Enter the amount you want to pay.';show('details')}
function startScanner(){show('scanner');if(!navigator.mediaDevices?.getUserMedia){$('#scannerMessage').textContent='Camera is not available in this browser.';return}navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}}).then(s=>{stream=s;$('#video').srcObject=s;$('#video').play();$('#scannerMessage').textContent='Searching for QR code…';requestAnimationFrame(scanFrame)}).catch(()=>$('#scannerMessage').textContent='Camera permission was denied or unavailable.')}
function stopScanner(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function scanFrame(){if(!stream||!$('#scanner').classList.contains('active'))return;const v=$('#video'),c=$('#canvas');if(v.readyState>=2&&v.videoWidth){c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d');x.drawImage(v,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height);if(window.jsQR){const code=jsQR(d.data,d.width,d.height,{inversionAttempts:'dontInvert'});if(code){const p=parseUPI(code.data);if(p){stopScanner();setDetails(p);return}$('#scannerMessage').textContent='QR found, but it is not a supported UPI payment QR.'}}}requestAnimationFrame(scanFrame)}
function buildPlan(total){const max=1999.99;if(total<=2000)return [total];const count=Math.ceil(total/max);const amounts=[];let remaining=Math.round(total*100)/100;for(let i=0;i<count;i++){const part=i===count-1?remaining:max;amounts.push(Math.round(part*100)/100);remaining=Math.round((remaining-part)*100)/100}return amounts}
function preparePayment(){const total=Number($('#amount').value);if(!total||total<=0){$('#amountHint').textContent='Please enter a valid amount.';return}state.amount=Math.round(total*100)/100;state.plan=buildPlan(state.amount);state.currentIndex=0;renderApps();show('apps')}
function makeUPI(amount){return 'upi://pay?'+new URLSearchParams({pa:state.upiId,pn:state.name||'UPI Merchant',am:Number(amount).toFixed(2),cu:'INR',tr:`UPIPAY${Date.now()}${state.currentIndex+1}`})}
function launchUPI(){const amount=state.plan[state.currentIndex]??state.amount;const item={id:Date.now(),name:state.name,upiId:state.upiId,total:state.amount,amount:Number(amount),status:'pending',app:'UPI App',part:state.currentIndex+1,totalParts:state.plan.length,time:new Date().toISOString()};localStorage.setItem('upiLastPayment',JSON.stringify(item));state.returning=true;location.href=makeUPI(amount);setTimeout(()=>{if(document.visibilityState==='visible')show('returnConfirm')},1300)}
function renderApps(){const totalParts=state.plan.length,amount=state.plan[state.currentIndex]??state.amount,isSplit=totalParts>1;$('#payStep').textContent=isSplit?`PAYMENT ${state.currentIndex+1} OF ${totalParts}`:'SINGLE PAYMENT';$('#paymentNoticeTitle').textContent=isSplit?`Your ₹${state.amount.toFixed(2)} is split into ${totalParts} payments`:'Your payment is ready';$('#paymentNoticeText').textContent=isSplit?'Click the button below to choose any installed UPI app. After returning, confirm it and the next installment will appear automatically.':'Click the button below to choose any installed UPI app.';$('#paySummary').textContent=`₹${amount.toFixed(2)}`;$('#progressBar').style.width=`${((state.currentIndex+1)/totalParts)*100}%`;$('#progressText').textContent=`${state.currentIndex+1}/${totalParts}`;$('#upiPayBtn').innerHTML=`<span class="upi-pay-icon">↗</span><span><b>Pay ₹${amount.toFixed(2)} via any UPI App</b><small>PhonePe · Google Pay · Paytm · BHIM & more</small></span><strong>›</strong>`;$('#upiPayBtn').onclick=launchUPI}
function markPart(status){const x=JSON.parse(localStorage.getItem('upiLastPayment')||'null');if(!x)return;x.status=status;const h=JSON.parse(localStorage.getItem('upiHistory')||'[]');h.unshift(x);localStorage.setItem('upiHistory',JSON.stringify(h.slice(0,50)));localStorage.removeItem('upiLastPayment')}
function nextAfterReturn(ok){const x=JSON.parse(localStorage.getItem('upiLastPayment')||'null');if(!x)return show('home');markPart(ok?'paid':'cancelled');if(ok&&state.currentIndex+1<state.plan.length){state.currentIndex++;state.returning=false;renderApps();show('apps')}else{state.returning=false;loadHistory();show('history')}}
function loadHistory(){const h=JSON.parse(localStorage.getItem('upiHistory')||'[]');$('#historyList').innerHTML=h.length?h.map(x=>`<div class="history-item"><div><b>${x.name||x.upiId}</b><div class="muted">${x.app||'UPI'} · ${x.totalParts>1?`Part ${x.part}/${x.totalParts} · `:''}${new Date(x.time).toLocaleString()}</div></div><div class="history-right"><b>₹${x.amount.toFixed(2)}</b><div class="badge ${x.status}">${x.status}</div></div></div>`).join(''):`<div class="empty-card"><b>No payments yet</b><p>Your local payment history will appear here.</p></div>`}
$('#scanBtn').onclick=startScanner;
$('#manualBtn').onclick=()=>{ $('#manualUpiId').value='';$('#manualName').value='';$('#manualHint').textContent='Example: merchant@okaxis';show('manual') };
$('#manualContinueBtn').onclick=()=>{const id=$('#manualUpiId').value.trim().toLowerCase();const name=$('#manualName').value.trim()||'UPI Merchant';if(!/^[^\s@]+@[^\s@]+$/.test(id)){$('#manualHint').textContent='Please enter a valid UPI ID, for example merchant@okaxis.';return}$('#manualUpiId').value=id;setDetails({upiId:id,name,amount:''})};
$('#stopScanBtn').onclick=()=>{stopScanner();show('home')};
$('#continueBtn').onclick=preparePayment;
$('#newPaymentBtn').onclick=()=>{localStorage.removeItem('upiLastPayment');state.returning=false;show('home')};
$('#completedBtn').onclick=()=>nextAfterReturn(true);$('#notCompletedBtn').onclick=()=>nextAfterReturn(false);$('#clearHistoryBtn').onclick=()=>{localStorage.removeItem('upiHistory');loadHistory()};
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{stopScanner();show(b.dataset.back)});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='history')loadHistory();show(b.dataset.nav)});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.returning)setTimeout(()=>{const x=JSON.parse(localStorage.getItem('upiLastPayment')||'null');if(x){$('#returnText').innerHTML=`<strong>₹${x.amount.toFixed(2)}</strong> to ${x.name||x.upiId}${x.totalParts>1?`<br><span class="muted">Part ${x.part} of ${x.totalParts}</span>`:''}`;$('#returnStep').textContent=x.totalParts>1?`PAYMENT ${x.part} OF ${x.totalParts}`:'PAYMENT';show('returnConfirm')}},250)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));loadHistory();
